GoogleChromeLabs/quicklink

package.json
Looks to be testing dependency only 👍
=> Fix: Move Puppeteer to "devDependencies" list

src/index.mjs, test/test-static-url-list.html
reviewers proposed: @lukeed @mathiasbynens
=> feat(index.mjs): normalize URLs being prefetched (fixes #27)

src/index.mjs, src/prefetch.mjs
Additional 🏌️ which can be reverted individually as requested.
Brings the library from 741B to 672B with no breaking changes this time~
---
Half-expecting the last commit to be reverted 😆
=> Golfing, Pt 2

README.md
=> docs(README): add URL fragments note about ignores (#52, #49)

package.json
change from:
`https://github.com/addyosmani/quicklink.git`
to:
`https://github.com/GoogleChromeLabs/quicklink.git`
=> Update repo path in package.json

translations/zh-cn/README.md
Hi @addyosmani , I've finished the translation work for the latest README.md. Pls review it. :P
=> docs(README): add simplified Chinese version for README.md (#36)

README.md
=> Update the Readme and add a mention of the WordPress plugin

README.md
This mentions instant.page and its technical difference from quicklink.
=> Mention instant.page as a related project

demos/basic.html
Not needed for HTML5 documents
=> remove unneeded type="text/css"  from demo page

demos/network-idle.html
and update polyfill.io to v3.
REF:
https://polyfill.io/v3/
https://google.github.io/styleguide/htmlcssguide.html#type_Attributes
=> remove unneeded type="text/css"  from demo

package.json
Can be useful to have there here:
ref:
- https://docs.npmjs.com/files/package.json#homepage
- https://docs.npmjs.com/files/package.json#bugs
=> Add homepage and bugs links to package.json

README.md
Adding sub-section with considerations to take for sites monetizing through ads.
cc // @addyosmani
=> Update docs with ad-related considerations

package.json, test/quicklink.spec.js, test/test-allow-origin-all.html, yarn.lock
The build has recently been failing with ~3 tests proving flaky post the 2.0.0-alpha landing in master. This PR aims to address these issues to allow us to continue moving forward with new changes.
=> [infra] Fix tests

site/src/_includes/components/over-prefetching.njk, site/src/index.njk
Section covering techniques to avoid over-prefetching with Quicklink.
=> Over-prefetching section for home page

package.json
See package.json docs https://docs.npmjs.com/files/package.json#files
=> Publish dist directory

package.json, src/react-chunks.js, yarn.lock
I've just removed dev console logs.
=> Spa hoc touches

test/quicklink.spec.js
=> fix occurrences typo

site/src/_includes/layouts/head.njk
BTW it seems there's a 404 in `noscript` referencing `solarized-dark.min.css`.
EDIT: removed `solarized-dark.min.css` in #328
=> site: move meta charset first

.github/workflows/size-limit.yml, .size-limit.json, package-lock.json, package.json
Feel free to tweak the limits, change to `@size-limit/preset-small-lib` or something else.
Since we aren't using Bundlewatch integration, this is an alternative solution.
=> Replace bundlewatch with size-limit

site/src/_includes/components/github-fork.njk, site/src/_includes/components/github-star.njk
Not sure if we should move this to _data, if so let me know!
=> site: fix github-fork/star label

site/package-lock.json, site/package.json
Things look like they still work as before, but needs another pair of eyes :)
=> site: update devDependencies

site/src/_includes/components/github-fork.njk, site/src/_includes/components/github-star.njk, site/src/_includes/components/use-with.njk, site/src/demo.njk, site/src/measure.njk
Also, remove redundant units from dimensions
=> site: specify loading lazy for more images

test/quicklink.spec.js
=> tests: switch to `uvu/assert` and its methods

site/.eleventy.js, site/package-lock.json, site/package.json
* remove wrong `templateFormants` option
* ES6-ify
* move htmlminifer config to a const
* return early
Non-whitespace diff: https://github.com/GoogleChromeLabs/quicklink/pull/351/files?w=1
=> Tweak .eleventy.js

site/src/_data/site.json, site/src/sitemap.njk
This is a sort of naive way but it seems to do the job.
~~EDIT: draft because I want to reuse the url variable in all places while at it.~~
=> site: add a sitemap and social tag fixes

.eslintignore, package.json, site/src/_includes/js/vendor/cssrelpreload.js, site/src/_includes/layouts/head.njk
Note that I didn't add a jsmin filter since htmlminifier already takes care of minification for us in production.
=> site: move csspreload.js to an include

site/src/script.js
This is only noticeable on development because we don't minify the HTML, but I guess it shouldn't hurt. :)
=> site: trim clipboard text

site/.eleventy.js, site/package-lock.json, site/package.json, site/src/_data/site.json, site/src/_includes/layouts/header.njk, site/src/api.njk, site/src/approach.njk, site/src/demo.njk, site/src/index.njk, site/src/measure.njk
I feel like this approach is the proper one without us having to maintain anything outside of the front matter.
BTW @addyosmani how about setting up Netlify previews? If you make an account, you can add me as an admin on Netlify temporarily so that I set it up, and then you can remove me.
=> site: switch to @11ty/eleventy-navigation

site/src/_includes/layouts/head.njk
=> site: fix `og:url` and remove `twitter:site`

site/src/assets/styles/prism.css
It's better for a11y, although it probably doesn't look too nice. :/
I tested a few more official themes and this was one of the few themes that didn't have color contrast issues.
=> site: switch to prism tomorrow theme

package.json
Reverts GoogleChromeLabs/quicklink#424
=> Revert "package.json: add a netlify script"

.github/workflows/ci.yml
@addyosmani I went with this solution for now. Feel free to adapt later if needed :)
=> CI: disable AppArmor
