demos/network-idle.js

Hi team,
I noticed two alerts flagged by [LGTM.com](https://lgtm.com/projects/g/GoogleChromeLabs/quicklink/alerts) on lines 28-29 of `network-idle.js`: the negation operator `!` binds more tightly than `in`. As a result, JavaScript will convert the string `'MessageChannel'` to a boolean (empty string is converted to `true`), before negating it and therefore checking whether `false` is a member of `window`. I imagine that's not what was intended here. Some more info: https://lgtm.com/rules/9980081/
This PR fixes both alerts — the last two in this repo :slightly_smiling_face:! If you like, you can enable LGTM's automated code review for pull requests to make sure that alerts like these (and more serious security issues) never get (re)introduced. For example, the AMPHTML project uses that to …

Fix wrong operator precedence in network-idle.js

---

README.md

I think it's useful to provide information on browser support for the Network Information API as detecting if the user is on a slow connection one of the key features.

docs: clarify Network Information API browser support

---

package.json

The `unpkg.com` service looks for an `"unpkg"` key initially, falling back to the `"main"` entry.
Since our `"main"` is CommonJS, this will break any & all `unpkg.com` links unless one has knowledge of the `dist/*` contents.
This adds that `unpkg` path, allowing the README example link to work.
---
_Closes #39_

Fix: Use "unpkg" entry path

---

README.md
src/index.mjs
test/quicklink.spec.js
test/test-allow-origin-all.html
test/test-allow-origin.html
test/test-ignore-basic.html
test/test-ignore-multiple.html
test/test-same-origin.html

Pulled my snippet from #31 into a PR.
The `origins` option is a list of permitted hostnames. The `sameOrigin` option indicates whether or not the domain's origin is all that's allowed. 
The use of `origins` and `sameOrigin` are mutually exclusive. If one has additional origins to allow, they should include their own within the larger `origins` array.
Adds 47 bytes in total.
---
_Closes #31, #33, and #38_

feat(restrict to same origins, add ignores)

---

README.md

Browsers should use the UMD file (unless importing as ES modules).
ref: https://github.com/GoogleChromeLabs/quicklink/issues/39
cc: @lukeed

fix(README): use UMD file for <script> tags

---

src/index.mjs
src/prefetch.mjs

This PR introduces a few quick size optimizations, mainly inlining the `options` handling to avoid the call to `Object.assign()` (instead applying defaults throughout the exported function).
One thought I had was that hoisting these defaults into constants would be free (they get inlined by microbundle/terser) and bring back some of the visibility lost from removing the assign().
/cc @lukeed

Size optimizations

---

package.json

There are no breaking changes from 0.7 -> 0.9. Size remains the same.

Update microbundle to fix "missing JSX plugin" issue

---

README.md

This commit adds a small note mentioning the [Quicklink module for Drupal](https://www.drupal.org/project/quicklink).

Add note to README about Drupal module.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

These issue templates may help to reduce support requests and cut down on back and forth getting details of reported issues.
Fixes: #107

GitHub Issue Templates

---

README.md

safer and saves a HTTP redirect

HTTPS link to nodejs.org

---

README.md

Safari 12.1 shipped Intersection Observer.

Mention Safari ≥ 12.1 working without polyfills

---

src/index.mjs

This avoids throwing an error on Safari ≤ 12.0.

Fail silently, don’t throw an error, when IntersectionObserver isn’t available

---

src/request-idle-callback.mjs

Fixes the following error when not transpiled:
> Uncaught ReferenceError: Cannot access 'requestIdleCallback' before initialization
>   at request-idle-callback.mjs:18
It doesn’t throw when being transpiled to ES5 because it uses `var` instead of `const`.

Check if `requestIdleCallback` exists in `window`

---

package.json
yarn.lock

@addyosmani cc @demianrenzulli 
1. moved `route-manifest` from `devDependencies` to `dependencies` in order for it to be available in the target project
2. adjusted `react` & `react-dom` versions
3. removed `babel-preset-env` in favor of `@babel/preset-env`

Spa hoc touches

---

.vscode/settings.json
src/chunks.mjs
src/index.mjs

This PR fixes a `Cannot read property 'then' of undefined` error that gets thrown when this condition is met:
```
if (conn = navigator.connection) {
// Don't prefetch if using 2G or if Save-Data is enabled.
if (conn.saveData || /2g/.test(conn.effectiveType)) return;
}
```
`prefetch` is meant to return a Promise, however in this instance it returns `undefined`, meaning that this throws:
```
prefetch(entry.href, options.priority).then(isDone).catch(err => {
isDone(); if (options.onError) options.onError(err);
});
```
I tried to add tests for this, but I could not figure out a way of mocking either `saveData` or a 2g connection - I tried multiple approaches, with none working. If anyone has any ideas then I'm happy to add the tests to cover this.

Fix: Cannot read property 'then' of undefined

---

README.md
site/src/api.njk
src/index.mjs
test/quicklink.spec.js
test/test-delay.html

📒 _This is an alternative to #213 without using data-attributes_
Added the `delay` option, which is useful to prevent QuickLink from prefetching too much links and have a heavy impact on CDN and servers.
> Type: `Number`
> Default: `0`
> 
> The _amount of time_ each link needs to stay inside the viewport before being prefetched, in milliseconds.
Unlike `throttle` option which prefetches the links in order of appearance, this option makes sure the links _currently inside the viewport_ are prefetched.
So for example, having 40 links in the page and users scrolling down fast to the 40th...
- with `throttle: 4`, QuickLink prefetches the first 4 links, then the 5th, 6th, 7th ... and finally the 40th
- with `delay: 500`, QuickLink prefetches only the first ones that are in viewport, then if …

Added `delay` option to reduce impact on CDNs and servers [alternative without data-attributes]

---

.gitattributes

In the search results are displayed **Nunjucks**, which is not conducive to users to find
Warehouse language before and after comparison:

chore: Modify repository default languages

---

README.md
src/index.mjs
test/quicklink.spec.js
test/test-node-list.html

Took some inspiration from PR [183](https://github.com/GoogleChromeLabs/quicklink/pull/183) from @cajotafer.
Proposal: Allow to observe links specified via a specific NodeList collection of Anchor Elements.

Added support to observe a specific Anchor NodeList collection

---

.eslintrc.js
package-lock.json
package.json
src/react-chunks.js

The eslint-config-google seems to be archived, but things seems to still work AFAICT.
We could switch to another config later.
There's one warning which I have no idea how to fix, so any help is welcome:
> Warning: React version not specified in eslint-plugin-react settings.
> See https://github.com/jsx-eslint/eslint-plugin-react#configuration

Update ESLint to v8 and add eslint-plugin-react

---

demos/basic.html
demos/hrefFn/hrefFn_demo.html
demos/network-idle.html
test/index.html
test/quicklink.spec.js
test/rmanifest.json
test/test-allow-origin-all.html
test/test-allow-origin.html
test/test-basic-usage.html
test/test-custom-dom-source.html
test/test-custom-href-function.html
test/test-delay.html
test/test-es-modules.html
test/test-ignore-basic.html
test/test-ignore-multiple.html
test/test-limit.html
test/test-node-list.html
test/test-prefetch-chunks.html
test/test-prefetch-duplicate-shared.html
test/test-prefetch-duplicate.html
test/test-prefetch-multiple.html
test/test-prefetch-single.html
test/test-prerender-andPrefetch.html
test/test-prerender-only.html
test/test-prerender-wrapper-multiple.html
test/test-prerender-wrapper-single.html
test/test-same-origin.html
test/test-threshold.html
test/test-throttle.html

If we still need the polyfill let me know and I'll just keep the formatting changes.
Non-whitespace diff: https://github.com/GoogleChromeLabs/quicklink/pull/316/files?w=1

tests: remove IntersectionObserver script and format HTML files

---

site/src/_includes/layouts/head.njk

highlightjs was removed in b91872b

site: remove the unused highlightjs preload and `noscript` fallback

---

site/src/_includes/layouts/base.njk

site: remove unneeded type from script

---

.eslintrc.js
src/chunks.mjs
src/index.mjs
src/prefetch.mjs
src/prerender.mjs
src/react-chunks.js
src/request-idle-callback.mjs
test/quicklink.spec.js

The 3rd parameter in `prerender` and `prefetch` are moot after https://github.com/GoogleChromeLabs/quicklink/commit/383e4955b9264716a61ce11a7e1931584f0b59b4, but I'll let you verify @addyosmani.
If you think we should bring it back let me know.
This patch saves a few bytes.
BTW Happy to revert any changes if you prefer the old way. :)
Non-whitespace diff: https://github.com/GoogleChromeLabs/quicklink/pull/312/files?w=1

Lint tweaks

---

.github/workflows/size-limit.yml
package.json

@addyosmani I believe this is what was the original intention? Before, prepare ran after npm install which was annoying.
Feel free to close if the PR is wrong :)

Replace prepare with `prepublishOnly`

---

.editorconfig
README.md
site/src/_includes/components/react.njk
site/src/api.njk

There might be another way to fix this, but I'm not too familiar with eleventy, so this fixes the `<br>`s shown for now :)
Another solution would be to switch these to a list in README and api.
Let me know which solution you prefer!

site: Backport fixes from README

---

site/src/robots.njk

Should give us more flexibility later if we add Netlify previews and we want to block them from indexing.

site: add a robots.txt file

---

site/.eleventy.js
site/src/_includes/layouts/base.njk
site/src/_includes/layouts/head.njk
site/src/_includes/layouts/header.njk

This should be more safe in case the base is changed and it's less stuff to handle manually in templates.
See https://www.11ty.dev/docs/plugins/html-base/
Might need to rebase #361 after this one, or this one after #361

site: switch to using `EleventyHtmlBasePlugin`

---

site/src/_includes/components/use-with.njk

Ideally these images should have width and height attributes too, but it should do the job for now, I guess.

site: specify loading=lazy for "Use With" images

---

site/src/_includes/layouts/header.njk
site/src/assets/styles/main.css

Preview:
---
I didn't preload the image @addyosmani, let me know if you think we should.
* main: https://google-chrome-labs-quicklink.netlify.app/
* this PR: https://deploy-preview-360--google-chrome-labs-quicklink.netlify.app/

site: move navbar logo to the HTML

---

.size-limit.json
package.json
src/chunks.mjs
src/index.mjs
src/prefetch.mjs
src/prerender.mjs
test/quicklink.spec.js

Dear @addyosmani @XhmikosR ,
I am submitting this pull request to address issues encountered within our Luxottica e-commerce group, where we observed inconsistent resource prefetching behavior across different browsers.
Currently, three prefetching methods are implemented:
1. **viaDom** – Prefetches resources without checking the `Access-Control-Allow-Origin` header, using the attribute `crossorigin="anonymous"`.
2. **viaXhr** – Fetches resources while always validating the `Access-Control-Allow-Credentials` response header.
3. **viaFetch** – Executes a fetch request that defaults to `mode: "cors"` and checks `Access-Control-Allow-Origin`, while `credentials: "include"` ensures `Access-Control-Allow-Credentials` validation.
Additionally, I have handled resource prioritization for Safari …

CROSSORIGIN and CREDENTIALS on prefetch requests

---

src/prefetch.mjs

prefetchOnHover: drop filter after `querySelectorAll`
